
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: webservers
spec:
  selector:
    app: tow123-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer